name: task_manager
description: "A clean and modern minimal To-Do application built with Flutter."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Tool used to generate launcher icons automatically from an image file
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # Register your assets folder path here so Flutter knows where to look for images
  assets:
    - lib/assets/icon.png

# Configuration settings for your app icon generator tool
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/icon.png"
  remove_alpha_ios: true